// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/urandom/kd/k8s (interfaces: ObjectMetaGetter)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	reflect "reflect"
)

// MockObjectMetaGetter is a mock of ObjectMetaGetter interface
type MockObjectMetaGetter struct {
	ctrl     *gomock.Controller
	recorder *MockObjectMetaGetterMockRecorder
}

// MockObjectMetaGetterMockRecorder is the mock recorder for MockObjectMetaGetter
type MockObjectMetaGetterMockRecorder struct {
	mock *MockObjectMetaGetter
}

// NewMockObjectMetaGetter creates a new mock instance
func NewMockObjectMetaGetter(ctrl *gomock.Controller) *MockObjectMetaGetter {
	mock := &MockObjectMetaGetter{ctrl: ctrl}
	mock.recorder = &MockObjectMetaGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockObjectMetaGetter) EXPECT() *MockObjectMetaGetterMockRecorder {
	return m.recorder
}

// GetObjectKind mocks base method
func (m *MockObjectMetaGetter) GetObjectKind() schema.ObjectKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectKind")
	ret0, _ := ret[0].(schema.ObjectKind)
	return ret0
}

// GetObjectKind indicates an expected call of GetObjectKind
func (mr *MockObjectMetaGetterMockRecorder) GetObjectKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectKind", reflect.TypeOf((*MockObjectMetaGetter)(nil).GetObjectKind))
}

// GetObjectMeta mocks base method
func (m *MockObjectMetaGetter) GetObjectMeta() v1.Object {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectMeta")
	ret0, _ := ret[0].(v1.Object)
	return ret0
}

// GetObjectMeta indicates an expected call of GetObjectMeta
func (mr *MockObjectMetaGetterMockRecorder) GetObjectMeta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectMeta", reflect.TypeOf((*MockObjectMetaGetter)(nil).GetObjectMeta))
}
